FORT = gfortran-12

OPTC = O2

algen_dir = ../../TOOLIB/ALGEN
chole_dir = ../../TOOLIB/CHOLE
digis_dir = ../../TOOLIB/DIGIS
fftw3_dir = ../../TOOLIB/FFTW3
files_dir = ../../TOOLIB/FILES
gplot_dir = ../../TOOLIB/GPLOT
intpl_dir = ../../TOOLIB/INTPL
least_dir = ../../TOOLIB/LEAST
minim_dir = ../../TOOLIB/MINIM
msolv_dir = ../../TOOLIB/MSOLV
qsort_dir = ../../TOOLIB/QSORT
splin_dir = ../../TOOLIB/SPLIN
tchev_dir = ../../TOOLIB/TCHEV
utils_dir = ../../TOOLIB/UTILS

abbot_dir = ../ABBOT
aniso_dir = ../ANISO
asfc2_dir = ../ASFC2
deriv_dir = ../DERIV
filtr_dir = ../FILTR
morph_dir = ../MORPH
stats_dir = ../STATS

