calcul_asfc – TPGLIB
calcul_asfc Subroutine
20 statements
Source File
private subroutine calcul_asfc(tab_in, scal, asfc_res, omp)
Return the asfc of a surface regarding the default parameter method_asfc
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in), dimension(1:scal%xres, 1:scal%yres) :: tab_in
input surface
type(SCALE_SURF), intent(in) :: scal
surface characteristics
real(kind=R8), intent(out), dimension(1:2) :: asfc_res
result: asfc, adjustment factor
logical(kind=I4), intent(in) :: omp
with openmp ?
Calls
Source Code
   subroutine calcul_asfc(tab_in, scal, asfc_res, omp)
   !================================================================================================
   !! Return the *asfc* of a surface regarding the default parameter *method_asfc*
   implicit none
   type(SCALE_SURF), intent(in )                                      :: scal     !! *surface characteristics*
   real   (kind=R8), intent(in ), dimension(1:scal%xres, 1:scal%yres) :: tab_in   !! *input surface*
   real   (kind=R8), intent(out), dimension(1:2)                      :: asfc_res !! *result: asfc, adjustment factor*
   logical(kind=I4), intent(in )                                      :: omp      !! *with openmp ?*
      if (out_lin) call get_unit(unit_out_lin)
      if (out_spl) call get_unit(unit_out_spl)
      select case(method_asfc)
         case(lin_all)
            call calcul_asfc_lin_all(tab_in, scal, asfc_res)
         case(spl_all)
            call calcul_asfc_spl_all(tab_in, scal, asfc_res)
         case(hermite)
            call calcul_asfc_hermite(tab_in, scal, asfc_res, omp)
         case default
            stop 'no valid method'
      endselect
   return
   endsubroutine calcul_asfc
Call graph
calcul_asfc calls get_unit, calcul_asfc_hermite, calcul_asfc_lin_all, calcul_asfc_spl_all
calcul_asfc_hermite calls get_unit, lmder1, omp_get_num_procs, df_boltz, dnq_et_i, dnq_xi_i, f_boltz, init_beta_boltz, locate, locate2, nq_i
calcul_asfc_lin_all calls lmder1, calcul_aire, df_boltz, f_boltz, init_beta_boltz, locate
calcul_asfc_spl_all calls db2ink, db2val, lmder1, calcul_aire, df_boltz, f_boltz, init_beta_boltz, locate
dnq_et_i calls dn_i, n_i
dnq_xi_i calls dn_i, n_i
nq_i calls n_i