dn_i – TPGLIB
dn_i Function
18 statements
Source File
private function dn_i(xi, i)
1D shape function derivative, quadratic case.
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in) :: xi
integer(kind=I4), intent(in) :: i
Return Value real(kind=r8)
Called by
Call graph
dnq_et_i calls dn_i
dnq_xi_et_i calls dn_i
dnq_xi_i calls dn_i
calcul_asfc_hermite calls dnq_et_i, dnq_xi_i
calcul_asfc calls calcul_asfc_hermite
test_asfc calls calcul_asfc_hermite