locate – TPGLIB
locate Function
28 statements
Source File
private function locate(n, xx, x)
Note
Function that returns the location of an element in a vector.
Given an array xx(1: n) , and given a value x , it returns a value j such that x is between xx(j) and xx(j + 1).
xx must be monotonic, either increasing or decreasing. j = 0 or j = n is returned to indicate that x is out of range.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4), intent(in) :: n
vector length
real(kind=R8), intent(in), dimension(1:n) :: xx
vector
real(kind=R8), intent(in) :: x
value to locate
Return Value integer(kind=i4)
Called by
Call graph
calcul_asfc_hermite calls locate
calcul_asfc_lin_all calls locate
calcul_asfc_spl_all calls locate
calcul_asfc calls calcul_asfc_hermite, calcul_asfc_lin_all, calcul_asfc_spl_all
test_asfc calls calcul_asfc_hermite