n_i – TPGLIB
n_i Function
18 statements
Source File
private function n_i(xi, i)
1D shape function, quadratic case.
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in) :: xi
integer(kind=I4), intent(in) :: i
Return Value real(kind=r8)
Called by
Call graph
dnq_et_i calls n_i
dnq_xi_i calls n_i
nq_i calls n_i
calcul_asfc_hermite calls dnq_et_i, dnq_xi_i, nq_i
calcul_asfc calls calcul_asfc_hermite
test_asfc calls calcul_asfc_hermite