nq_i – TPGLIB
nq_i Function
44 statements
Source File
private function nq_i(xi, et, i, j)
2D shape function, quadratic case.
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in) :: xi
real(kind=R8), intent(in) :: et
integer(kind=I4), intent(in) :: i
integer(kind=I4), intent(in) :: j
Return Value real(kind=r8)
Calls
Called by
Call graph
nq_i calls n_i
calcul_asfc_hermite calls nq_i
calcul_asfc calls calcul_asfc_hermite
test_asfc calls calcul_asfc_hermite