std_array – TPGLIB
std_array Subroutine
14 statements
Source File
public subroutine std_array(tab, mx)
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(inout), dimension(..) :: tab
1D array
type(moment_stat), intent(out), optional :: mx
moment_stat statistical moments
Calls
Source Code
   subroutine std_array(tab, mx)
   implicit none
   real(kind=R8), intent(inout), dimension(..) :: tab    !! *1D array*
   type(moment_stat), intent(out), optional    :: mx     !! [[moment_stat]] *statistical moments*
      select rank (tab)
         rank (1)
            call std_array1D(tab, mx)
         rank (2)
            call std_array2D(tab, mx)
         rank default
            stop "bad rank in 'std_array'"
      endselect
   return
   endsubroutine std_array
Call graph
std_array calls std_array1d, std_array2d
std_array1d calls calc_moments
std_array2d calls calc_moments
calc_moments calls calc_moments_1d